version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

    commands:
        # Clear npm cache to avoid issues with corrupted archives
        - npm cache clean --force
        
        # Install dependencies
        - npm install
        
        # Install babel plugin
        - npm install --save-dev @babel/plugin-proposal-private-property-in-object
        
        # Optionally update ESLint to avoid deprecated version
        - npm install eslint@latest --save-dev
        
        # Check node and npm versions for debugging purposes
        - node -v
        - npm -v

  build:
    commands:
        # Run build script
        - npm run-script build

artifacts:
  # Include all files required to run the application
  # Exclude node_modules to avoid overwriting issues on deploy
  files:
    - public/**/*
    - src/**/*
    - package.json
    - index.js
    - appspec.yml
    - scripts/**/*
