version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      # Clear npm cache to prevent corrupt tarball issues
      - npm cache clean --force
      
      # Install dependencies
      - npm install

  build:
    commands:
      # Run the build script
      - npm run build

artifacts:
  files:
    - public/**/*
    - dist/**/*
    - package.json
    - package-lock.json
    - index.js
    - appspec.yml
    - scripts/**/*
