version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  # Ensure Node.js v20.x.x is used, as 20.17.x is included in this version series
    commands:
      - echo Installing project dependencies...
      - npm install  # Install dependencies from package.json

  build:
    commands:
      - echo Building the React app...
      - npm run build  # Build the React app (ensure `build` is defined in package.json)

  post_build:
    commands:
      - echo Packaging build artifacts...
      - mkdir -p build-artifacts  # Create a directory to store the build output
      - cp -r build/* build-artifacts/  # Copy build files to the artifacts directory
      - echo Build artifacts prepared successfully

artifacts:
  files:
    - build-artifacts/**/*  # Specify the files to be uploaded as build artifacts
