version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      # Force clean npm cache to avoid corrupted cache
      - npm cache clean --force
      # Optional: Add a delay to ensure cache clean completes
      - sleep 10
      # Update npm to the latest stable version
      - npm install -g npm@latest
      # Install dependencies with verbose logging for debugging
      - npm install --verbose

  build:
    commands:
      # Run the build script
      - npm run-script build

artifacts:
  # Include all files required to run the application
  files:
    - public/**/*
    - src/**/*
    - package.json
    - package-lock.json
    - index.js
    - appspec.yml
    - scripts/**/*
  discard-paths: yes
  exclude:
    - node_modules/**/*
