version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies
      - npm install -g npm
  build:
    commands:
      - echo Building the React app
      - npm run build
  post_build:
    commands:
      - echo Preparing for deployment
      - zip -r react-app.zip build appspec.yml scripts/
artifacts:
  files:
    - react-app.zip
